THEMES = {
    "Agentic AI": {
        "keywords": ["agentic AI", "agentic", "AI agent", "autonomous agent", "エージェントAI", "tool-calling", "tool use", "multi-agent", "agent framework", "LLM agent"],
        "color": "#4F8EF7",
        "rss_feeds": [
            ("Hugging Face Blog", "https://huggingface.co/blog/feed.xml"),
            ("Langchain", "https://blog.langchain.dev/feed.xml"),
            ("TechCrunch AI", "https://techcrunch.com/category/artificial-intelligence/feed/"),
            ("VentureBeat AI", "https://venturebeat.com/category/ai/feed/"),
            ("MIT Tech Review", "https://www.technologyreview.com/feed/"),
        ],
        "arxiv_query": "(cat:cs.AI OR cat:cs.LG OR cat:cs.CL) AND (abs:\"agentic\" OR abs:\"AI agent\" OR abs:\"autonomous agent\" OR abs:\"agent framework\" OR ti:\"agentic\" OR ti:\"agent\")",
    },
    "ゲーミフィケーション": {
        "keywords": ["gamification", "game mechanics", "gamified", "loyalty program", "loyalty", "light buyer", "light user", "customer engagement", "reward program", "ゲーミフィケーション", "ロイヤルティ", "ライトバイヤー", "behavioral economics", "user retention"],
        "color": "#F76F4F",
        "rss_feeds": [
            ("Gamesbrief", "https://www.gamesbrief.com/feed/"),
            ("GDC Vault", "https://www.gdcvault.com/rss.xml"),
            ("Gamasutra", "https://www.gamedeveloper.com/rss.xml"),
            ("Yu-kai Chou", "https://yukaichou.com/feed/"),
            ("Interaction Design Foundation", "https://www.interaction-design.org/feed"),
            ("Nielsen Norman", "https://www.nngroup.com/feed/rss/all/"),
            ("Medium - Gamification", "https://medium.com/tag/gamification/feed"),
            ("ITmedia", "https://rss.itmedia.co.jp/rss/2.0/itmedia_all.xml"),
        ],
        "arxiv_query": "(cat:cs.AI OR cat:cs.HC OR cat:cs.LG OR cat:econ.GN) AND (abs:\"gamification\" OR abs:\"gamified\" OR abs:\"loyalty program\" OR abs:\"reward program\" OR abs:\"customer engagement\" OR abs:\"behavioral\" OR ti:\"gamification\" OR ti:\"loyalty\")",
    },
    "セマンティックレイヤー": {
        "keywords": ["semantic layer", "metrics layer", "headless BI", "knowledge graph", "ontology", "data modeling", "data warehouse", "data lakehouse", "セマンティックレイヤー", "オントロジー", "data mesh", "data catalog"],
        "color": "#4FBF8E",
        "rss_feeds": [
            ("dbt Blog", "https://www.getdbt.com/blog/rss.xml"),
            ("Databricks Blog", "https://databricks.com/blog/feed"),
            ("Looker Blog", "https://www.looker.com/blog/feed"),
            ("Mode Analytics", "https://mode.com/blog/feed/"),
            ("ThoughtWorks Technology Radar", "https://www.thoughtworks.com/radar/feed"),
            ("Towards Data Science", "https://towardsdatascience.com/feed"),
            ("Medium - Data Engineering", "https://medium.com/tag/data-engineering/feed"),
            ("Iceberg Blog", "https://iceberg.apache.org/blog/"),
            ("ZDNet Japan", "https://japan.zdnet.com/rss/index.rdf"),
        ],
        "arxiv_query": "(cat:cs.DB OR cat:cs.AI OR cat:cs.IR OR cat:cs.DC) AND (abs:\"semantic layer\" OR abs:\"knowledge graph\" OR abs:\"ontology\" OR abs:\"data warehouse\" OR abs:\"data mesh\" OR abs:\"data catalog\" OR ti:\"semantic\" OR ti:\"knowledge graph\")",
    },
}
